
quantities_dict = {
    "Number of continents on Earth": 7,
    "Days in a week": 7,
    "Months in a year": 12,
    "Hours in a day": 24,
    "Minutes in an hour": 60,
    "Seconds in a minute": 60,
    "Stars on the United States flag": 50,
    "Keys on a standard piano": 88,
    "Strings on a standard guitar": 6,
    "Strings on a violin": 4,
    "Keys on a standard keyboard": 104,
    "Buttons on an average TV remote": 40,
    "Episodes in a specific TV series season": 10,
    "Seasons in a particular TV series": 5,
    "Books in the 'Harry Potter' series": 7,
    "Films in the original 'Star Wars' trilogy": 3,
    "Players on a soccer team on the field": 11,
    "Players on a basketball team on the court": 5,
    "Players on a baseball team on the field": 9,
    "Soldiers in a specific military unit": 100,
    "Floors in the Eiffel Tower": 3,
    "Steps in the Leaning Tower of Pisa": 294,
    "Rooms in Buckingham Palace": 775,
    "Windows in Notre-Dame Cathedral": 113,
    "Sculptures in Park Güell": 60,
    "Pages in a particular book": 350,
    "Words in an average academic paper": 5000,
    "Letters in the English alphabet": 26,
    "Letters in the Hebrew alphabet": 22,
    "Member countries in the United Nations": 193,
    "Countries in the European Union": 27,
    "Regions in France": 18,
    "States in the United States": 50,
    "Provinces in Canada": 10,
    "States in Australia": 6,
    "Cities in Germany": 2055,
    "Islands in Indonesia": 17508,
    "Islands in the Philippines": 7641,
    "Rivers in Brazil": 12,
    "Mountains in the Himalayas exceeding 8,000 meters": 14,
    "Planets in the Solar System": 8,
    "Moons orbiting Jupiter": 79,
    "Elements in the periodic table": 118,
    "Bones in the adult human body": 206,
    "Teeth in a complete adult human set": 32,
    "Chromosomes in a human cell": 46,
    "Heart chambers in a human": 4,
    "Lobes in the human brain": 4,
    "Pairs of ribs in the human body": 12,
    "Muscles in the human body": 650
}
